### ISSUE TITLE
Please port to Python3.12

### ISSUE THREAD

**Issue by tillea** [tibonihoo/yapsy#18]
Hi,
Debian has packaged yapsy.  We try to migrate to Python3.12.  When testing yapsy
with Python3.12 in our [CI](https://salsa.debian.org/python-team/packages/yapsy/-/jobs/5132141#L1187) it fails with:

    testActivationAndDeactivation (test.test_SimplePlugin.SimpleTestCase.testActivationAndDeactivation)
    Test if the activation procedure works. ... Unable to import plugin: /builds/python-team/packages/yapsy/debian/output/source_dir/test/plugins/SimplePlugin
    Traceback (most recent call last):
      File "/builds/python-team/packages/yapsy/debian/output/source_dir/yapsy/PluginManager.py", line 518, in loadPlugins
        candidate_module = PluginManager._importModule(plugin_module_name, candidate_filepath)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/builds/python-team/packages/yapsy/debian/output/source_dir/yapsy/PluginManager.py", line 584, in _importModule
        candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
                                                                                                             ^^^^^^^^^^^^^
    AttributeError: type object 'Loader' has no attribute 'PY_SOURCE'
    FAIL
    ...

You can find the full log in our [CI](https://salsa.debian.org/python-team/packages/yapsy/-/jobs/5132141#L1187).

It would be great if you could port yapsy to Python3.12.

Kind regards
    Andreas.

**Comment by tillea** [comment]
I confirm this issue is solved by [PR11](https://github.com/tibonihoo/yapsy/pull/11)
